### ISSUE TITLE
Linux compile problems

### ISSUE THREAD

**Issue by Nerus87** [VoiDeD/sourcemod-sendproxy-manager#3]
Hi, please add release for Linux.

Regards,
Nerus.

**Comment by voided** [comment]
I don't have any plans to do official linux releases. If I remember correctly, you should be able to find unofficial linux builds in the AM forum thread.

**Comment by Nerus87** [comment]
If you mean about https://forums.alliedmods.net/showpost.php?p=2134833&postcount=267 it is from 2014.

**Comment by voided** [comment]
There have been no major changes since that binary was released, so it should be fine.

**Comment by Nerus87** [comment]
I'll try, but what I need to compile native "sendproxy manager" plugin for CSS on Linux (Debian x64 console only), gcc, make, Source SDK, MM Source code ?

**Comment by voided** [comment]
@powerlord would likely be the best person to ask about which compiler toolset you'll need. The included makefile should likely also be of some help.

**Comment by powerlord** [comment]
Oh yeah, we never did convert this over to use AMBuild, did we?

Anyway, AlliedModders in general tends to use Clang 3.4 or newer instead of gcc, but I'd have to ask @psychonic to be sure.  The others are pretty standard: Use the css branch of the Source SDK, the 1.10-dev branch of MetaMod: Source and the 1.7-dev branch of SourceMod.

You could instead use the master versions of MM:S and SM, but if you do the resulting extension may only work on MM:S 1.11 and SM 1.8.

**Comment by Nerus87** [comment]
@powerlord
MetaMod Source 1.10:
https://github.com/alliedmodders/metamod-source.git
SourceMod 1.7
https://github.com/alliedmodders/sourcemod.git
"Use the css branch of the Source SDK", you mean SKD of MM:S and SM or Source SDK like https://github.com/ValveSoftware/source-sdk-2013 ?

**Comment by powerlord** [comment]
AlliedModders have their own copies of the Source SDK.

In this case, I meant the css branch of [this source code](https://github.com/alliedmodders/hl2sdk).  If you're using command-line git, use `-b css` during the git clone operation.

SourceMod has a script named [checkout-deps.sh](https://github.com/alliedmodders/sourcemod/blob/master/tools/checkout-deps.sh) that checks out all of SourceMod's dependencies, including all available hl2sdks to different directories.

**Comment by Nerus87** [comment]
@VoiDeD nvm, waiting for AMBuild from @powerlord
@powerlord I tried to build your package but there is no interface file (some problem with paths ?):

```
In file included from /home/nerus/compile/sourcemod-sendproxy-manager/extension/extension.h:40:0,
                 from /home/nerus/compile/sourcemod-sendproxy-manager/extension/extension.cpp:34:
/home/nerus/compile/sourcemod-sendproxy-manager/extension/sdk/smsdk_ext.h:41:27: fatal error: IExtensionSys.h: There is no any file or catalog
 #include <IExtensionSys.h>
```

**Comment by powerlord** [comment]
OK, apparently GitHub doesn't notify you when a comment is updated...

I take it the above is from ambuild? Odd, it should be able to locate `IExtensionSys.h` as long as it can find SourceMod's source files (it checks a few environment variables for it).

If it's detecting the wrong directory, you can call `configure.py` with `--sm-path [sourcemod-path-here]`  to override its detected location. (I use this to test it against SM 1.7 and 1.8)
